/**
 * routes/api/pokeapi.js — Pokémon data API backed by cached Pokémon Showdown data.
 *
 * Endpoints:
 *   GET /api/v1/pokeapi/pokemon/:name  — Pokémon data (types, moves with secondary effects,
 *                                        sprite, breed/legendary/fossil flags)
 *   GET /api/v1/pokeapi/move/:name     — Move data (type, category, power, accuracy, PP,
 *                                        secondary_status, secondary_volatile, secondary_boosts)
 *
 * Data is loaded from JSON files generated by scripts/fetch-showdown-data.js.
 * Responses are cached in-process (node-cache) for the lifetime of the process.
 *
 * Move name normalisation: Showdown slugs have no hyphens (e.g. "icepunch").
 * Requests using hyphenated names (e.g. "ice-punch") are normalised automatically.
 *
 * @ref https://play.pokemonshowdown.com/data/
 */
'use strict';

const fs        = require('fs');
const path      = require('path');
const express   = require('express');
const router    = express.Router();
const rateLimit = require('express-rate-limit');
const NodeCache = require('node-cache');

const cache = new NodeCache({ stdTTL: 3600, checkperiod: 600 });

const limiter = rateLimit({
  windowMs: 60 * 1000,
  max: 60,
  message: { error: 'Too many Pokédex requests — please slow down.' },
  standardHeaders: true,
  legacyHeaders: false,
});
router.use(limiter);

// Allow test overrides via environment variable
const CACHE_DIR = process.env.POKEMON_CACHE_DIR
  || path.join(__dirname, '..', '..', 'public', 'cache');

// ── Lazy-loaded Showdown data ────────────────────────────────────────────────
let _pokemonMap = null;  // Showdown slug → pokemon entry
let _movesMap   = null;  // Showdown slug → move entry
let _learnsets  = null;  // Showdown slug → { learnset: { moveKey: [...] } }

function loadShowdownData() {
  if (_pokemonMap && _movesMap && _learnsets) return true;
  try {
    if (!_pokemonMap) {
      const list = JSON.parse(
        fs.readFileSync(path.join(CACHE_DIR, 'pokemon-list.json'), 'utf8')
      );
      _pokemonMap = Object.fromEntries(list.map(p => [p.name, p]));
    }
    if (!_movesMap) {
      _movesMap = JSON.parse(
        fs.readFileSync(path.join(CACHE_DIR, 'showdown-moves.json'), 'utf8')
      );
    }
    if (!_learnsets) {
      _learnsets = JSON.parse(
        fs.readFileSync(path.join(CACHE_DIR, 'showdown-learnsets.json'), 'utf8')
      );
    }
    return true;
  } catch (e) {
    console.warn('[pokeapi] Showdown cache not ready:', e.message,
      '\n  → run: node scripts/fetch-showdown-data.js');
    return false;
  }
}

/** Normalise a move name to a Showdown key: lowercase, no hyphens or spaces. */
const toShowdownKey = name => (name || '').toLowerCase().replace(/[- ]/g, '');

// ── GET /pokemon/:name ───────────────────────────────────────────────────────
router.get('/pokemon/:name([a-z0-9][a-z0-9-]*)', (req, res) => {
  const nameParam = req.params.name.toLowerCase();
  const slug      = toShowdownKey(nameParam);
  const cacheKey  = `poke:mon:${slug}`;

  const hit = cache.get(cacheKey);
  if (hit) return res.json(hit);

  if (!loadShowdownData()) {
    return res.status(503).json({
      error: 'Pokédex data unavailable — run: node scripts/fetch-showdown-data.js',
    });
  }

  const p = _pokemonMap[slug] || _pokemonMap[nameParam];
  if (!p) {
    return res.status(404).json({ error: `Pokémon '${nameParam}' not found` });
  }

  // Build move list from learnset, enriched with move data
  const learnsetEntry = _learnsets[slug] || _learnsets[nameParam] || null;
  const moveKeys      = learnsetEntry ? Object.keys(learnsetEntry.learnset || {}) : [];
  const moves         = moveKeys.map(mk => _movesMap[mk] || {
    name: mk, displayName: mk, type: null, damage_class: null,
    power: null, accuracy: null, pp: null,
    secondary_status: null, secondary_volatile: null,
    secondary_chance: null, secondary_boosts: null, effect: '',
  });

  const data = {
    id:           p.id,
    name:         p.name,
    displayName:  p.displayName,
    sprite:       p.sprite,
    types:        p.types,
    moves,
    is_legendary: p.is_legendary,
    is_mythical:  p.is_mythical,
    can_breed:    p.can_breed,
    is_fossil:    p.is_fossil,
  };

  cache.set(cacheKey, data);
  res.json(data);
});

// ── GET /move/:name ──────────────────────────────────────────────────────────
router.get('/move/:name([a-z0-9][a-z0-9-]*)', (req, res) => {
  const nameParam = req.params.name.toLowerCase();
  const slug      = toShowdownKey(nameParam);
  const cacheKey  = `poke:move:${slug}`;

  const hit = cache.get(cacheKey);
  if (hit) return res.json(hit);

  if (!loadShowdownData()) {
    return res.status(503).json({
      error: 'Move data unavailable — run: node scripts/fetch-showdown-data.js',
    });
  }

  const m = _movesMap[slug] || _movesMap[nameParam];
  if (!m) {
    return res.status(404).json({ error: `Move '${nameParam}' not found` });
  }

  cache.set(cacheKey, m);
  res.json(m);
});

/** Reset cached Showdown data — used in tests to reload from a different directory. */
router._resetCache = () => { _pokemonMap = null; _movesMap = null; _learnsets = null; };

module.exports = router;
